#!/usr/bin/env bash

for f in *.jpg; do
    [[ -e "${f}" ]] || continue
    case "$(file --brief "${f}")" in
        HTML\ *)   git mv -v "${f}" nao_imagem/"${f%.jpg}.html" ;;
        XML\ *)    git mv -v "${f}" nao_imagem/"${f%.jpg}.xml" ;;
        ASCII\ *)  git mv -v "${f}" nao_imagem/"${f%.jpg}.txt" ;;
        PNG\ *)        git mv -v "${f}" "${f%.jpg}.png" ;;
        GIF\ *)        git mv -v "${f}" "${f%.jpg}.gif" ;;
        *Web/P\ image) git mv -v "${f}" "${f%.jpg}.webp" ;;
    esac
done
