#!/usr/bin/env bash
## usage example:
## ./resize_all.sh 320 533 ./experimento_1f ./experimento_1f/resized
#
# This script calls resize_image, and therefore the output image format can be
# chosen via the `IMAGE_FORMAT` environment variable, which should be an image
# file extension (without the leading dot) supported by ImageMagick.  If
# `IMAGE_FORMAT` is unset then keep the current image format of each file.
#
# Beware: `resize_image` uses ImageMagick's convert, which silently overwrites
# existing files.  `resize_image` does check the existence of the output file
# before calling `convert`, but this is a race condition.

set -o nounset

declare -ir W="$1"              # Target width
declare -ir H="$2"              # Target height
declare -r INDIR="$3"           # Input directory
declare -r OUTDIR="$4"          # Output directory

for F in "${INDIR}"/*; do
    [[ -f "${F}" ]] || continue
    echo "Converting ${F}" >&2
    ./resize_image "${W}" "${H}" "${F}" "${OUTDIR}"
done
