#!/usr/bin/env bash
set -o nounset

declare -r REFDIR="$1"          # Reference directory
declare -r INDIR="$2"           # Input directory
declare -r OUTDIR="$3"          # Output directory

for F in "${REFDIR}"/*; do
    [[ -f "${F}" ]] && printf "%s\\0" "${INDIR}/$(basename "${F%.jpg}.png")"
done | xargs --null git mv -i -t "${OUTDIR}"
